### ISSUE TITLE
At the moment can't run on ios

### ISSUE THREAD

**Issue by thanhdevapp** [vikrantnegi/react-native-location-tracking#1]
I clone and follow your guide but can't run on ios

/Volumes/Samsung_T5/react-native-location-tracking-master/ios/Pods/Google-Maps-iOS-Utils/src/Heatmap/GMUGradient.h:16:9: fatal error: 'UIKit/UIKIt.h' file not found

**Comment by vikrantnegi** [comment]
Just cloned the repo and its working fine at my end. 

Did you install the pods before running the app?

go to the ios directory `cd ios` and install the pods by `pod install`.

**Comment by vikrantnegi** [comment]
I've updated the react native and other code. Please check if this issue still exists. I'm closing this issue. If you are still facing this let me know.
