### ISSUE TITLE
Android Location need to be turned on Manually in Genymotion Emulator 

### ISSUE THREAD

**Issue by Ahmed-Imam** [vikrantnegi/react-native-location-tracking#2]
I need to go to android Setting to allow the location or it shows me an error Looks like your app doesn't have the permission to access location. Add the following to your AndroidManifest.xml 
android.permission.ACCESS_FINE_LOCATION"
even though I already added it. how can ask for the location when the app starts as it is in the IOS?

**Comment by vikrantnegi** [comment]
I think you might need to explicitly ask for location permission. I'm using (react-native-permission)[https://github.com/yonahforst/react-native-permissions] for that.
Try using it, works fine at my end.
