### ISSUE TITLE
It doesn't show the accurate location on Android

### ISSUE THREAD

**Issue by Ahmed-Imam** [vikrantnegi/react-native-location-tracking#3]
I tried it on real devices, it works fine on IOS but on Android Note 3, it doesn't show my current location 
it shows some where in India ??

**Comment by vikrantnegi** [comment]
What version of android are you using?

**Comment by Ahmed-Imam** [comment]
5.0

**Comment by vikrantnegi** [comment]
@Ahmed-Imam Hi, I've not checked on this older device. Can you check if it works on newer Android devices for you?

**Comment by ankurk91** [comment]
@vikrantnegi 
May you can mention min SDK version in readme.
