### ISSUE TITLE
Invariant violation

### ISSUE THREAD

**Issue by manishmodha** [vikrantnegi/react-native-location-tracking#4]
Invariant Violation: [27,"AIRMapMarker",111,{"coordinate":{"latitude":29.95539,"longitude":78.07513,"latitudeDelta":"<<NaN>>","longitudeDelta":"<<NaN>>"},"position":"absolute","backgroundColor":0}] is not usable as a native method argument

**Comment by vikrantnegi** [comment]
This is an issue with react-native-maps here [#2861](https://github.com/react-native-community/react-native-maps/issues/2681).

I've updated the react native with the issue fix. Please check if this is fixed.
